const signup=require('../controller/UserController/signup')
const signin=require('../controller/UserController/signin')
const addAccount=require('../controller/AccountController/addAccount')
const getAccountsByUserId=require('../controller/AccountController/getAccountsByUserId')
const getAccountBalance=require('../controller/AccountController/getAccountBalance')
const getAccountNameById=require('../controller/AccountController/getAccountNameById')
const addTransaction=require('../controller/TransactionController/addTransaction')
const editTransaction=require('../controller/TransactionController/editTransaction')
const deleteTransaction=require('../controller/TransactionController/deleteTransaction')
const getTransactionsByAccountName=require('../controller/TransactionController/getTransactionsByAccountName')
const getTransactionById=require('../controller/TransactionController/getTransactionById')
const express=require('express')
const routes=express.Router();
routes.post('/signup',signup)
routes.post('/signin',signin)
routes.post('/addAccount',addAccount)
routes.get('/getAccountsByUserId',getAccountsByUserId)
routes.get('/getAccountBalance',getAccountBalance)
routes.get('/getAccountNameById',getAccountNameById)
routes.post('/addTransaction',addTransaction)
routes.put('/editTransaction',editTransaction)
routes.delete('/deleteTransaction',deleteTransaction)
routes.get('/getTransactionsByAccountName',getTransactionsByAccountName)
routes.get('/getTransactionById',getTransactionById)
module.exports=routes;